serviceMonitor:
  enabled: true
  namespace: monitoring
  labels:
    release: prometheus-stack

prometheusRule:
  enabled: false

config:
  datasource:
    host: postgres
    user: postgres
    database: fk
    passwordSecret:
      name: database
      key: POSTGRES_PASSWORD
    sslmode: disable
