serviceMonitor:
  enabled: true
  namespace: monitoring
  labels:
    release: prometheus-stack

prometheusRule:
  enabled: false

config:
  datasource:
    # Specify one of both datasource or datasourceSecret
    host: database-api
    user: postgres
    database: fkweb
    passwordSecret:
      name: database-api-secret
      key: POSTGRES_PASSWORD
    sslmode: disable
