##
# For end users
##
kind: IngressRoute
apiVersion: traefik.containo.us/v1alpha1
metadata:
  name: media-ingress
  namespace: "{{ namespace }}"
spec:
  tls:
    certResolver: default
  entryPoints: 
    - websecure
  routes:
  - match: Host(`{{ domain }}`) && PathPrefix(`/media`)
    kind: Rule
    services:
    - kind: Service
      name: rook-ceph-rgw-media-store
      namespace: rook-ceph
      scheme: http
      port: 80
