apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis
  namespace: "{{ namespace }}"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: media-processor
  namespace: "{{ namespace }}"
spec:
  selector:
    matchLabels:
      app: media-processor
  minReadySeconds: 5
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: media-processor
    spec:
      containers:
      - name: media-processor
        image: frikanalen/media-processor
        imagePullPolicy: Always
        env:
          - name: PORT
            value: "8000"
          - name: REDIS_URL
            value: "redis://redis:6379"
          - name: FK_API
            value: "https://{{ domain }}/api/v2"
          - name: FK_API_KEY
            valueFrom:
              secretKeyRef:
                name: fk-api-key
                key: FK_API_KEY
        envFrom:
          - secretRef:
              name: media
          - configMapRef:
              name: media
        ports:
          - name: web
            containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: media-processor
  name: media-processor
  namespace: "{{ namespace }}"
spec:
  ports:
  - name: web
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: media-processor
---
