apiVersion: apps/v1
kind: Deployment
metadata:
  name: media-processor
  namespace: "{{ namespace }}"
spec:
  selector:
    matchLabels:
      app: media-processor
  minReadySeconds: 5
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: media-processor
    spec:
      volumes:
      - name: shared-data
        emptyDir: {}
      containers:
      - name: media-processor
        image: frikanalen/media-processor
        imagePullPolicy: Always
        env:
          - name: REDIS_URL
            value: "redis://redis:6379"
          - name: FK_API
            value: "https://{{ domain }}/api/v2"
          - name: FK_API_KEY
            valueFrom:
              secretKeyRef:
                name: fk-api-key
                key: FK_API_KEY
        envFrom:
          - secretRef:
              name: media
          - configMapRef:
              name: media
        ports:
          - name: web
            containerPort: 8001
          - name: webhooks
            containerPort: 8002
        volumeMounts:
        - name: shared-data
          mountPath: /app/tmp-upload
      - name: tusd
        image: tusproject/tusd
        command: ["tusd"]
        args: ["-hooks-http", "http://media-processor:8002/tusd-hooks", "-hooks-http-forward-headers", "Authorization", "-behind-proxy", "-hooks-enabled-events", "pre-finish", "-base-path", "/api/v2/media/upload"]
        volumeMounts:
        - name: shared-data
          mountPath: /srv/tusd-data/data
        ports:
        - name: upload
          containerPort: 1080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: media-processor
  name: media-processor
  namespace: "{{ namespace }}"
spec:
  ports:
  - name: upload
    port: 1080
    protocol: TCP
    targetPort: 1080
  - name: web
    port: 8001
    protocol: TCP
    targetPort: 8001
  - name: webhooks
    port: 8002
    protocol: TCP
    targetPort: 8002
  selector:
    app: media-processor
---
