apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: strip-apiv2-prefix
  namespace: "{{ namespace }}"
spec:
  stripPrefix:
    prefixes:
      - /api/v2/
---
kind: IngressRoute
apiVersion: traefik.containo.us/v1alpha1
metadata:
  name: media-processor
  namespace: "{{ namespace }}"
spec:
  tls:
    certResolver: default
  entryPoints:
    - websecure
  routes:
  - match: Host(`{{ domain }}`) && PathPrefix(`/api/v2/upload/video`)
    kind: Rule
    middlewares:
      - name: strip-apiv2-prefix
        namespace: "{{ namespace }}"
    services:
    - name: media-processor
      kind: Service
      scheme: http
      port: 8000