apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: "{{ namespace }}"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  minReadySeconds: 5
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: frikanalen/frontend-v2:latest
        # NB: Remember this is a Next.JS project and as a result
        # the values of these at build time are also significant!
        env:
          - name: NEXT_PUBLIC_FK_MEDIA
            value: https://{{ domain }}/media
          - name: NEXT_PUBLIC_FK_GRAPHQL
            value: https://{{ domain }}/graphql
          - name: NEXT_PUBLIC_FK_API
            value: https://{{ domain }}/api/v2
          - name: NEXT_PUBLIC_FK_UPLOAD
            value: https://{{ domain }}/api/v2/media/upload
          - name: NEXT_PUBLIC_FK_MEDIAPROC
            value: https://{{ domain }}/api/v2/media
        imagePullPolicy: Always
        ports:
          - name: web
            containerPort: 3000
        readinessProbe:
          httpGet:
            path: /healthz
            port: 3000
          initialDelaySeconds: 10
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3000
---
kind: Service
apiVersion: v1
metadata:
  name: frontend
  namespace: "{{ namespace }}"
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 3000
      name: web
---
kind: IngressRoute
apiVersion: traefik.containo.us/v1alpha1
metadata:
  name: frontend
  namespace: "{{ namespace }}"
spec:
  tls:
    certResolver: default
  entryPoints:
    - websecure
  routes:
  - match: Host(`{{ domain }}`)
    kind: Rule
    services:
    - name: frontend
      kind: Service
      scheme: http
      port: 3000
      sticky:
        cookie:
          httpOnly: true
          name: fk-load-balancer
          secure: true
          sameSite: none
