apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: styring-cors
  namespace: "{{ namespace }}"
spec:
  headers:
    customResponseHeaders:
      Access-Control-Allow-Origin: "*"
      Access-Control-Allow-Headers: "Content-Type, Access-Control-Allow-Headers, Authorization, X-Requested-With"
      Access-Control-Allow-Methods: "POST"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: styring
  namespace: "{{ namespace }}"
spec:
  selector:
    matchLabels:
      app: styring
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: styring
    spec:
      containers:
        - name: styring
          image: frikanalen/styring:latest
          ports:
            - name: web
              containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: styring
  namespace: "{{ namespace }}"
spec:
  type: ClusterIP
  selector:
    app: styring
  ports:
    # Three types of ports for a service
    # nodePort - a static port assigned on each the node
    # port - port exposed internally in the cluster
    # targetPort - the container port to send requests to
    - protocol: TCP
      port: 80
      name: web
---
kind: IngressRoute
apiVersion: traefik.containo.us/v1alpha1
metadata:
  name: atem-control
  namespace: "{{ namespace }}"
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{ domain }}`) && PathPrefix(`/playout`)
      kind: Rule
      middlewares:
        - name: styring-cors
          namespace: "{{ namespace }}"
      services:
        - kind: Service
          name: styring
          scheme: http
          port: 80
  tls:
    certResolver: default
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: styring-api-prefix
  namespace: "{{ namespace }}"
spec:
  stripPrefix:
    prefixes:
      - /api/atem
