apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: kafka
  labels:
    name: kafka
spec:
  ports:
  - port: 9092
    name: kafka-port
    protocol: TCP
  selector:
    app: kafka
  type: LoadBalancer
---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: kafka
  name: kafka
  namespace: kafka
spec:
  replicas: 1
  selector:
    app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: wurstmeister/kafka
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_ADVERTISED_PORT
          value: "9092"
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: "kafka-service.kafka"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zk-cs.kafka:2181
        - name: KAFKA_BROKER_ID
          value: "0"
        - name: KAFKA_CREATE_TOPICS
          value: new-video-uploaded:1:1
