apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: scheme-redirect
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
kind: IngressRoute
apiVersion: traefik.containo.us/v1alpha1
metadata:
  name: scheme-redirect-rook-ceph-dash
  namespace: rook-ceph
spec:
  entryPoints: 
    - web
  routes:
  - match: Host(`ceph.frikanalen.no`)
    priority: 100
    kind: Rule
    services:
    - kind: Service
      name: rook-ceph-mgr-dashboard
      namespace: rook-ceph
      scheme: http
      port: 7000
    middlewares:
      - name: scheme-redirect
---
kind: IngressRoute
apiVersion: traefik.containo.us/v1alpha1
metadata:
  name: rook-ceph-dash
  namespace: rook-ceph
spec:
  entryPoints: 
    - websecure
  routes:
  - match: Host(`ceph.frikanalen.no`)
    kind: Rule
    services:
    - kind: Service
      name: rook-ceph-mgr-dashboard
      namespace: rook-ceph
      scheme: http
      port: 7000
  tls:
    certResolver: default
