language: python
dist: xenial
python:
  - "3.5"
  - "3.6"
install:
  - pip install -r requirements-dev.txt
  - pip install -r upload/requirements.txt
script: make test
cache: pip
addons:
  apt:
    packages:
      - bs1770gain
