apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegram-bot
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegram-bot
  template:
    metadata:
      labels:
        app: telegram-bot
    spec:
      containers:
      - name: telegram-bot
        image: vientoprojects/kubernetes-monitoring-telegram-bot:latest
        env:
        - name: TELEGRAM_BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: telegram-config
              key: apiSecret
---
apiVersion: v1
kind: Service
metadata:
  name: telegram-bot
  namespace: monitoring
spec:
  selector:
    app: telegram-bot
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
