apiVersion: batch/v1
kind: Job
metadata:
  name: load-initial-data
spec:
  template:
    spec:
      containers:
      - name: django
        image: frikanalen/django-backend
        args:
          - ./manage.py
          - loaddata
          - frikanalen
        env:
          - name: DJANGO_SETTINGS_MODULE
            value: fkweb.settings.production
          - name: DATABASE_HOST
            value: database-api
          - name: DATABASE_USER
            value: fkweb
          - name: DATABASE_NAME
            value: fkweb
          - name: ALLOWED_HOSTS
            value: frikanalen.no,fk.dev.local
          - name: SMTP_SERVER
            value: smtp.uio.no
        envFrom:
        - secretRef:
            name: postgres-secret-django
      restartPolicy: OnFailure
