# TODO: Need a Program that represents a generic program on disk w/o being scheduled
# TODO: Program that represents the following: jukebox, dead air, pause, program guide, ident

from database import Video
from . import clock
from vision.configuration import configuration

import datetime

class Program(object):
    """
    program_start
        datetime
    media_id
        integer
    playback_offset
        None or float in seconds
    playback_duration
        None or float in seconds

    TODO: perhaps specify a "pase" media_id or somethign?
    """
    def __init__(self, media_id=None, program_start=None, playback_offset=None, title=None, playback_duration=None, data={}, filename=None, loop=False):
        self.program_start = program_start
        self.media_id = media_id
        self.playback_offset = playback_offset
        self.playback_duration = playback_duration
        self.title = title
        self.data = data
        self.filename = filename
        self.loop = loop

    def get_filename(self):
        if self.filename is not None:
            return self.filename

        if configuration.mediaAssets.scheme == 'https':
            video = Video(self.media_id).files['theora']
            video = configuration.mediaAssets.baseURL + video
        else:
            video = Video(self.media_id).files['broadcast']
            if video is None:
                video = Video(self.media_id).files['original']

        return video

    def seconds_since_scheduled_start(self):
        dt = (clock.now() - self.program_start)
        return dt.seconds + dt.microseconds / 1e6

    def seconds_until_playback(self):
        dt = (self.program_start - clock.now())
        return dt.seconds + dt.microseconds / 1e6

    def seconds_until_end(self):
        duration = self.playback_duration
        if not duration:
            duration = self.get(duration)
        if not duration:
            raise Exception("No duration given for video %i" % self.media_id)
        dt = (self.program_start - clock.now())
        return dt.seconds + dt.microseconds / 1e6 + duration

    def endTime(self):
        return self.program_start + datetime.timedelta(seconds=self.playback_duration)

    def __repr__(self):
        return "<Program <Scheduled for [%s]-[%s]> <Video #%i: [%s]>>" % \
            (self.program_start, self.endTime(), self.media_id, self.title)

    @classmethod
    def fromWeirdLegacyDict(cls, weirdDict, playbackOffset = 0.0, additionalData = None):
        """ Loads the weird dict generated by ScheduledVideo """
        d = weirdDict
        return cls(
                    media_id=d["broadcast_location"],
                    program_start=d["starttime"],
                    playback_offset=playbackOffset,
                    playback_duration=d["duration"] / 1000.,
                    title=d["name"],
                    # unused:
                    # endtime, video_id, header, schedule_reagion....
                    data=additionalData
                    )
