---
- name: Add volunteers to user database
  hosts: all
  become: true
  gather_facts: false
  roles:
    - common
  tags: common
- name: Install upload app
  hosts: upload
  become: true
  gather_facts: false
  roles:
    - upload-app
- name: Set up web server
  hosts: web
  become: true
  gather_facts: false
  roles:
    - web
