version: "2"
services:
  fk-stream-webm:
    image: "jrottenberg/ffmpeg"
    user: "nobody"
    # these are set in .env
    environment:
      - SOURCE
      - DESTINATION
    command: "-i ${SOURCE} -f webm -cluster_size_limit 2M -cluster_time_limit 5100 -content_type video/webm -c:a libvorbis -b:a 192K -c:v libvpx -b:v 1.2M -g 5 -crf 25 -deadline good -speed 3 -legacy_icecast 1 -threads 5 ${DEST}"
