kind: Service
apiVersion: v1
metadata:
  name: monitoring-stream-http-incoming
spec:
  type: ClusterIP
  externalIPs:
    - 192.168.3.100
  externalTrafficPolicy: Cluster
  selector:
    app: monitoring-stream-ws
  ports:
    - protocol: TCP
      port: 8081
      name: http
  type: LoadBalancer
---
kind: Service
apiVersion: v1
metadata:
  name: monitoring-stream-ws
spec:
  type: ClusterIP
  selector:
    app: monitoring-stream-ws
  ports:
    - protocol: TCP
      port: 8082
      name: ws
