apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
data:
  Corefile: |
    .:53 {
        errors
        health {
           lameduck 5s
        }
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
           pods insecure
           fallthrough in-addr.arpa ip6.arpa
           ttl 30
        }
        hosts {
            192.168.3.1   simula.frikanalen.no        simula
            192.168.3.10  obe-hd.frikanalen.no
            192.168.3.33  tx1.frikanalen.no        tx1
            192.168.3.34  tx2.frikanalen.no        tx2
            192.168.3.35  tx3.frikanalen.no        tx3
            192.168.3.36  tx4.frikanalen.no        tx4
            192.168.3.59  file01.frikanalen.no        file01
            192.168.3.240 fw1.frikanalen.no fw1
            192.168.3.100 forrige.frikanalen.no
            fallthrough
        }
        prometheus :9153
        forward . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
    }
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: system:coredns
rules:
  - apiGroups:
    - ""
    resources:
    - endpoints
    - services
    - pods
    - namespaces
    verbs:
    - list
    - watch
  - apiGroups:
    - discovery.k8s.io
    resources:
    - endpointslices
    verbs:
    - list
    - watch
