---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: traefik-acme-storage
  namespace: kube-system
  labels:
    type: local
spec:
  storageClassName: rook-ceph-block
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/traefik-acme-storage"
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    component: "server"
    app: traefik
  name: traefik-acme-storage
  namespace: default
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "100Mi"
