---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: traefik-certstore
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: rook-ceph-block
