apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-frontend
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: frontend
  minReadySeconds: {{ .Values.minReadySeconds }}
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        env:
{{ toYaml .Values.env | indent 10 }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
          - name: web
            containerPort: 3000
        readinessProbe:
          httpGet:
            path: /healthz
            port: 3000
          initialDelaySeconds: {{ .Values.probe.initialDelaySeconds }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3000
{{ toYaml .Values.probe | indent 10 }}
