kind: Service
apiVersion: v1
metadata:
  name: upload-receiver
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: upload-receiver
  ports:
    - protocol: TCP
      port: 1080
      name: web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: upload-receiver
  namespace: default
spec:
  selector:
    matchLabels:
      app: upload-receiver
  replicas: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: upload-receiver
    spec:
      containers:
      - name: upload-receiver
        image: frikanalen/upload-receiver:latest
        volumeMounts:
        - name: secrets-volume
          mountPath: /secrets
        imagePullPolicy: Always
        ports:
          - name: web
            containerPort: 1080
        env:
          - name: FK_TOKEN
            valueFrom:
              secretKeyRef:
                name: upload-receiver
                key: FK_TOKEN
          - name: FK_API
            value: https://frikanalen.no/api
      volumes:
      - name: secrets-volume
        secret:
          secretName: upload-processors
          defaultMode: 0444
