apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: database
spec:
  selector:
    matchLabels:
      service: postgres
  replicas: 1
  template:
    metadata:
      annotations:
        co.elastic.logs/module: postgresql
      labels:
        service: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:12.2
          args: ['-c', 'shared_buffers=8GB']
          ports:
            - containerPort: 5432
          env:
            - name: TZ
              value: Europe/Oslo
            - name: POSTGRES_DB
              value: fkweb
            - name: POSTGRES_USER
              value: fkweb
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: DATABASE_PASS
          volumeMounts:
            - mountPath: "/var/lib/postgresql/data"
              name: postgres-data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-data
