apiVersion: batch/v1
kind: CronJob
metadata:
  name: jukebox
  namespace: beta
spec:
  schedule: "00 22 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: jukebox
            image: frikanalen/jukebox-v2:latest
            env:
              - name: FK_API
                value: "https://beta.frikanalen.no/api/v2"
              - name: FK_API_KEY
                valueFrom:
                  secretKeyRef:
                    name: fk-api-key
                    key: FK_API_KEY
          restartPolicy: OnFailure
