apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgraphile
spec:
  selector:
    matchLabels:
      app: postgraphile
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: postgraphile
    spec:
      containers:
      - name: postgraphile
        image: graphile/postgraphile:4
        envFrom:
        - secretRef:
            name: postgres-secret-graphql
        ports:
          - name: web
            containerPort: 5000
