apiVersion: batch/v1
kind: CronJob
metadata:
  name: fill-next-weeks-agenda
spec:
  schedule: "00 22 * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: django
        spec:
          restartPolicy: OnFailure
          containers:
            - name: django
              image: {{ .Values.image.django }}
              args:
                - ./manage.py
                - fill_next_weeks_agenda
                - -v
                - '2'
              env:
                - name: DJANGO_SETTINGS_MODULE
                  value: {{ .Values.env.DJANGO_SETTINGS_MODULE }}
                - name: ALLOWED_HOSTS
                  value: {{ .Values.env.ALLOWED_HOSTS }}
                - name: SMTP_SERVER
                  value: {{ .Values.env.SMTP_SERVER }}
                - name: SECRET_KEY
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Values.django.secretName }}
                      key: SECRET_KEY
                - name: DATABASE_URL
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Values.database.secret }}
                      key: DATABASE_URL
