{{- $existing := (lookup "v1" "Secret" .Release.Namespace .Values.databaseSecretName) }}
{{- if not $existing }}
apiVersion: v1
kind: Secret
metadata:
  name: {{  .Values.databaseSecretName }}
type: Opaque
{{- $djangoPassword := randAlphaNum 30 }}
data:
  superUserPassword: {{ randAlphaNum 30 | b64enc | quote }}
  replicationUserPassword: {{ randAlphaNum 30 | b64enc | quote }}
  djangoPassword: {{ $djangoPassword 30 | b64enc | quote }}
  DATABASE_URL: {{ printf "postgres://%s:%s@%s:%s/%s" .Values.database.user $password .Values.database.name .Values.database.port .Values.databaseName | b64enc | quote }}
{{- end }}