{{- $existing := (lookup "v1" "Secret" .Release.Namespace "django-secret") }}
{{- if not $existing }}
apiVersion: v1
kind: Secret
metadata:
  name: django-secret
type: Opaque
data:
  DJANGO_SECRET_KEY: {{ randAlphaNum 50 | b64enc | quote }}
{{- end }}
