apiVersion: batch/v1
kind: Job
metadata:
  name: django-load-fixtures
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: django-load-fixtures
      labels:
        app: django
    spec:
      restartPolicy: OnFailure
      containers:
        - name: loaddata
          image: {{ .Values.image.django }}
          imagePullPolicy: Always
          command: ["python", "manage.py", "loaddata", "frikanalen"]
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: {{ .Values.env.DJANGO_SETTINGS_MODULE }}
            - name: ALLOWED_HOSTS
              value: {{ .Values.env.ALLOWED_HOSTS }}
            - name: SMTP_SERVER
              value: {{ .Values.env.SMTP_SERVER }}
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.django.secretName }}
                  key: SECRET_KEY
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.secret }}
                  key: DATABASE_URL
