apiVersion: apps/v1
kind: Deployment
metadata:
  name: memcached
spec:
  selector:
    matchLabels:
      app: memcached
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: memcached
    spec:
      containers:
      - name: memcached
        image: {{ .Values.memcached.image }}
        ports:
          - name: memcached
            containerPort: 11211
---
kind: Service
apiVersion: v1
metadata:
  name: memcached
spec:
  type: ClusterIP
  selector:
    app: memcached
  ports:
    - protocol: TCP
      port: 11211
      name: memcached
