apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
  storageClassName: csi-rbd-sc
