env:
  browser: true
  es2021: true
extends:
  - airbnb
  - 'plugin:react/recommended'
  - 'prettier'
  - 'prettier/react'
  - 'plugin:@typescript-eslint/recommended'
  - "plugin:@typescript-eslint/recommended-requiring-type-checking"
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules: {}
