version: "2"
services:
  node:
    image: "node:10-alpine"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
      - PORT=3002
    volumes:
      - ./:/home/node/app
    expose:
      - "8081"
    command: "sh -c \"npm install && npm dev\""
