version: "2"
services:
  fk-frontend:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: "node:10-alpine"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
      - PORT=3002
    volumes:
      - ./:/home/node/app
    expose:
      - "3002"
    ports:
      - "3002:3002"
    command: "npm run dev -- -p 3002"
