apiVersion: apps/v1
kind: Deployment
metadata:
  name: playout
spec:
  selector:
    matchLabels:
      app: playout
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: playout
    spec:
      containers:
      - name: playout
        image: frikanalen/playout:latest
        imagePullPolicy: Always
        volumeMounts:
        - name: config-volume
          mountPath: /app/config.yaml
          subPath: config.yaml
        - name: tz-config
          mountPath: /etc/localtime
      volumes:
      - name: config-volume
        configMap:
          name: playout-config
      - name: tz-config
        hostPath:
          path: /usr/share/zoneinfo/Europe/Oslo
          type: File
