version: "3.1"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: fk
      POSTGRES_DB: fk
    ports:
      - 5432:5432

  db-adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080
