# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-12-01 15:51


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fk', '0002_organization_homepage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='is_filler',
            field=models.BooleanField(default=False, verbose_name=b'Play automatically?'),
        ),
    ]
