# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-15 23:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fk', '0005_add_created_time_for_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='upload_token',
            field=models.CharField(blank=True, default=b'', help_text=b'Code for upload', max_length=32),
        ),
    ]
