# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-03 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fk', '0006_video_upload_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='videofile',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, help_text=b'Time the video  file was created', null=True),
        ),
        migrations.AlterField(
            model_name='videofile',
            name='old_filename',
            field=models.CharField(default=b'', max_length=256),
        ),
    ]
