# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-19 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fk', '0007_auto_20170603_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='rgb',
        ),
        migrations.RemoveField(
            model_name='fileformat',
            name='rgb',
        ),
        migrations.AlterField(
            model_name='videofile',
            name='old_filename',
            field=models.CharField(blank=True, default=b'', max_length=256),
        ),
    ]
