# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-10 13:41
from __future__ import unicode_literals

import datetime

import durationfield.db.models.fields.duration
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fk', '0001_squashed_0008_remove_colorful_20180819_1810'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asrun',
            options={'ordering': ('-played_at', '-id')},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name', '-id'), 'verbose_name': 'video category', 'verbose_name_plural': 'video categories'},
        ),
        migrations.AlterModelOptions(
            name='fileformat',
            options={'ordering': ('fsname', '-id'), 'verbose_name': 'video file format', 'verbose_name_plural': 'video file formats'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ('name', '-id')},
        ),
        migrations.AlterModelOptions(
            name='scheduleitem',
            options={'ordering': ('-id',), 'verbose_name': 'TX schedule entry', 'verbose_name_plural': 'TX schedule entries'},
        ),
        migrations.AlterModelOptions(
            name='schedulepurpose',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'get_latest_by': 'uploaded_time', 'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='videofile',
            options={'ordering': ('-video_id', '-id'), 'verbose_name': 'video file', 'verbose_name_plural': 'video files'},
        ),
        migrations.RenameField(
            model_name='video',
            old_name='duration',
            new_name='duration_old',
        ),
        migrations.RenameField(
            model_name='scheduleitem',
            old_name='duration',
            new_name='duration_old',
        ),
        migrations.RenameField(
            model_name='weeklyslot',
            old_name='duration',
            new_name='duration_old',
        ),
        migrations.AddField(
            model_name='video',
            name='duration',
            field=models.DurationField(blank=True, default=datetime.timedelta(0)),
        ),
        migrations.AddField(
            model_name='scheduleitem',
            name='duration',
            preserve_default=False,
            field=models.DurationField(
                default=datetime.timedelta(0)),
        ),
        migrations.AddField(
            model_name='weeklyslot',
            name='duration',
            preserve_default=False,
            field=models.DurationField(
                default=datetime.timedelta(0)),
        ),
        migrations.AlterField(
            model_name='scheduleitem',
            name='duration_old',
            field=durationfield.db.models.fields.duration.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weeklyslot',
            name='duration_old',
            field=durationfield.db.models.fields.duration.DurationField(blank=True, null=True),
        ),
    ]
