{
 "title": "Traefik 2",
 "description": "Simple dashboard for Traefik 2",
 "tags": [
  "traefik",
  "load-balancer",
  "docker",
  "prometheus"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "label": "Job:", "query": "label_values(job)" },
   {
    "name": "protocol",
    "label": "Service:",
    "query": "label_values(traefik_service_requests_total, protocol)"
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "404 Error Count",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "expr": "sum(increase(traefik_service_requests_total{code=\"404\",protocol=~\"$protocol\"}[$interval]))"
    }
   ]
  },
  {
   "title": "503 Error count",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "expr": "sum(increase(traefik_service_requests_total{code=\"503\",protocol=~\"$protocol\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Top 5 $protocol return code",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 4, "x": 9, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "topk(5, sum(traefik_service_requests_total{protocol=~\"$protocol\"}) by (code))",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Average response time",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 13, "y": 0 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(traefik_entrypoint_request_duration_seconds_sum) / sum(traefik_entrypoint_requests_total) * 1000"
    }
   ]
  },
  {
   "title": "Average response time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(traefik_service_request_duration_seconds_sum{protocol=~\"$protocol\"}) / sum(traefik_entrypoint_requests_total{protocol=~\"$protocol\"}) * 1000",
     "legendFormat": "Average response time (ms)"
    }
   ]
  },
  {
   "title": "Bad Status Code Count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(traefik_service_requests_total{code=\"404\",method=\"GET\",protocol=~\"$protocol\"}[$interval])) by (service)",
     "legendFormat": "{{service}} "
    }
   ]
  },
  {
   "title": "Total requests",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_service_requests_total[$interval]))",
     "legendFormat": "Total requests"
    }
   ]
  },
  {
   "title": "Used sockets",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{job=~\"$job\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Access to services",
   "type": "graph",
   "gridPos": { "h": 6, "w": 14, "x": 10, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_service_requests_total{protocol=~\"http|https\"}[$interval])) by (service)",
     "legendFormat": "{{service}} "
    }
   ]
  },
  {
   "title": "ENTRYPOINT - Open Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(traefik_entrypoint_open_connections) by (method)",
     "legendFormat": "{{ method }}"
    }
   ]
  },
  {
   "title": "SERVICE - Open Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(traefik_service_open_connections) by (method)",
     "legendFormat": "{{ method }}"
    }
   ]
  },
  {
   "title": "Status Code Count ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(traefik_service_requests_total{protocol=~\"$protocol\"}[$interval])) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  }
 ]
}