apiVersion: apps/v1
kind: Deployment
metadata:
  name: toches
  namespace: beta
spec:
  selector:
    matchLabels:
      app: toches
  minReadySeconds: 5
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: toches
    spec:
      containers:
      - name: toches
        image: frikanalen/toches
        imagePullPolicy: Always
        env:
          - name: TZ
            value: Europe/Oslo
          - name: FK_MEDIA
            value: https://beta.frikanalen.no/media
          - name: FK_API_KEY
            valueFrom:
              secretKeyRef:
                name: fk-api-key
                key: FK_API_KEY
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: database
                key: DATABASE_URL
        ports:
          - name: caspar
            containerPort: 5500
            protocol: UDP
          - name: web
            containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: toches
  name: toches
  namespace: beta
spec:
  ports:
  - name: web
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: toches
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: strip-apiv2-prefix
  namespace: beta
spec:
  stripPrefix:
    prefixes:
      - /api/v2/
---
# I have to set this up this way because swagger-ui insists on getting static
# assets from /swagger. Please don't link directly to frikanalen.no/swagger,
# because At Some Point I'll figure out how to make swagger-ui use relative
# URLs
kind: IngressRoute
apiVersion: traefik.containo.us/v1alpha1
metadata:
  name: toches-swagger
  namespace: beta
spec:
  tls:
    certResolver: default
  entryPoints:
    - websecure
  routes:
  - match: Host(`beta.frikanalen.no`) && PathPrefix(`/swagger`)
    kind: Rule
    services:
    - name: toches
      namespace: beta
      kind: Service
      scheme: http
      port: 80
---
kind: IngressRoute
apiVersion: traefik.containo.us/v1alpha1
metadata:
  name: toches-graphql
  namespace: beta
spec:
  tls:
    certResolver: default
  entryPoints:
    - websecure
  routes:
  - match: Host(`beta.frikanalen.no`) && PathPrefix(`/graphql`)
    kind: Rule
    services:
    - name: toches
      namespace: beta
      kind: Service
      scheme: http
      port: 80
---
kind: IngressRoute
apiVersion: traefik.containo.us/v1alpha1
metadata:
  name: toches
  namespace: beta
spec:
  tls:
    certResolver: default
  entryPoints:
    - websecure
  routes:
  - match: Host(`beta.frikanalen.no`) && PathPrefix(`/api/v2`)
    kind: Rule
    middlewares:
      - name: strip-apiv2-prefix
        namespace: beta
    services:
    - name: toches
      namespace: beta
      kind: Service
      scheme: http
      port: 80
