apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-postgres-exporter
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app: prometheus-postgres-exporter
  namespaceSelector:
    matchNames:
      - beta
  endpoints:
    - port: exporter
      interval: 30s
      path: /metrics
