kind: IngressRoute
apiVersion: traefik.containo.us/v1alpha1
metadata:
  name: kiloview
  namespace: default
spec:
  entryPoints: 
    - websecure
  routes:
  - match: Host(`kiloview.frikanalen.no`)
    kind: Rule
    services:
    - kind: Service
      name: kiloview
      scheme: http
      port: 80
  tls:
    certResolver: default
