- hosts: localhost
  vars_files:
    - vault.yml
  vars:
    namespace: beta
    domain: beta.frikanalen.no
  tasks:
    - name: Create beta namespace
      k8s:
        name: "{{ namespace }}"
        api_version: v1
        kind: Namespace
        state: present

    - name: Set up backend
      community.kubernetes.k8s:
        state: present
        definition: "{{lookup ('template', 'beta/toches.yaml')}}"
