apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: frikanalen/frontend:latest
        imagePullPolicy: Always
        ports:
          - name: web
            containerPort: 3000
        envFrom:
          - configMapRef:
              name: frontend-envs
