- hosts: localhost
  name: Deploy database
  vars_files:
    - vault.yml
  vars:
    namespace: beta
    database_size: 500Mi
    database_replicas: 3
    postgres_version: 15
    db_user: fk
    db_host: postgres
    backups_nfs_path: /srv/nfs/pgbackups
    backups_nfs_host: 192.168.3.1
    # In Kubernetes CronJob syntax
    backup_schedule: "0 */1 * * *"
  tasks:
    - name: Create database URL
      ansible.builtin.set_fact:
        database_url: "postgresql://{{ db_user }}:{{ postgres_password }}@{{ db_host }}/fk"

    - name: Create NFS volume for database backups
      community.kubernetes.k8s:
        state: present
        definition: "{{ lookup('template', 'database/nfs-backup-volume.yaml') }}"

    - name: Install Kubegres
      community.kubernetes.k8s:
        state: present
        src: files/kubegres-1.16.yaml

    - name: Create Postgres secret
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          type: Opaque
          metadata:
            name: database
            namespace: "{{ namespace }}"
          stringData:
            DATABASE_URL: "{{ database_url }}"
            FKWEB_DATABASE_URL: "{{ fkweb_database_url }}"
            POSTGRES_PASSWORD: "{{ postgres_password }}"
            POSTGRES_REPLICATION_PASSWORD: "{{ replication_password }}"

    - name: Deploy Kubegres instance
      community.kubernetes.k8s:
        state: present
        definition: "{{ lookup('template', 'database/kubegres.yaml') }}"

    - name: Create database servicemonitor
      community.kubernetes.k8s:
        state: present
        definition: "{{ lookup('template', 'database/servicemonitor.yaml') }}"
