- hosts: localhost
  vars:
    namespace: beta
    domain: beta.frikanalen.no
  tasks:
    - name: Create namespace
      k8s:
        name: "{{ namespace }}"
        api_version: v1
        kind: Namespace
        state: present

    - name: Set up live packager
      community.kubernetes.k8s:
        state: present
        definition: "{{lookup ('template', 'stream-hls-pgm.yaml')}}"
