kind: IngressRoute
apiVersion: traefik.containo.us/v1alpha1
metadata:
  name: scheme-redirect-riot
  namespace: matrixorg
spec:
  entryPoints: 
    - web
  routes:
  - match: Host(`matrix.frikanalen.no`) 
    kind: Rule
    services:
    - kind: Service
      name: riot
      namespace: matrixorg
      scheme: http
      port: 8765
    middlewares:
      - name: scheme-redirect
        namespace: default
---
kind: IngressRoute
apiVersion: traefik.containo.us/v1alpha1
metadata:
  name: riot
  namespace: matrixorg
spec:
  entryPoints: 
    - websecure
  routes:
  - match: Host(`matrix.frikanalen.no`) 
    kind: Rule
    services:
    - kind: Service
      name: riot
      namespace: matrixorg
      scheme: http
      port: 8765
  tls:
    certResolver: default
