---
kind: IngressRoute
apiVersion: traefik.containo.us/v1alpha1
metadata:
  name: monitoring
  namespace: default
spec:
  entryPoints: 
    - websecure
  routes:
  - match: Host(`monitoring.frikanalen.no`)
    kind: Rule
    services:
    - kind: Service
      name: monitoring-stream-ws
      scheme: http
      port: 8082
  tls:
    certResolver: default
