apiVersion: apps/v1
kind: Deployment
metadata:
  name: schedule-service
spec:
  selector:
    matchLabels:
      app: schedule-service
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: schedule-service
    spec:
      containers:
      - name: schedule-service
        env:
          - name: DATABASE_HOST
            value: database-api
          - name: DATABASE_USER
            value: fkschedule
          - name: DATABASE_NAME
            value: fkweb
          - name: DATABASE_PASSWORD
            valueFrom:
               secretKeyRef:
                  name: database-api-secret
                  key: FKSCHEDULE_PASSWORD
          - name: TZ
            value: Europe/Oslo
        image: frikanalen/schedule-service:latest
        imagePullPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: schedule-service
spec:
  type: ClusterIP
  selector:
    app: schedule-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: web
