apiVersion: apps/v1
kind: Deployment
metadata:
  name: schedule-service
spec:
  selector:
    matchLabels:
      app: schedule-service
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: schedule-service
    spec:
      containers:
      - name: schedule-service
        image: frikanalen/schedule-service:latest
        imagePullPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: schedule-service
spec:
  type: ClusterIP
  selector:
    app: schedule-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: web
