# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-20 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleitem',
            name='schedulereason',
            field=models.IntegerField(blank=True, choices=[(1, 'Legacy'), (2, 'Administrative'), (3, 'User'), (4, 'Automatic'), (5, 'Jukebox')]),
        ),
    ]
