# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-01-01 11:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fk', '0004_is_filler_explained'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduleitem',
            name='duration_old',
        ),
        migrations.RemoveField(
            model_name='video',
            name='duration_old',
        ),
        migrations.RemoveField(
            model_name='weeklyslot',
            name='duration_old',
        ),
    ]
