# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-12-01 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fk', '0005_remove_duration_old'),
    ]

    operations = [
        migrations.AddField(
            model_name='videofile',
            name='integrated_lufs',
            field=models.FloatField(blank=True, null=True, verbose_name='Integrated LUFS of file defined in ITU R.128'),
        ),
        migrations.AddField(
            model_name='videofile',
            name='truepeak_lufs',
            field=models.FloatField(blank=True, null=True, verbose_name='True peak LUFS of file defined in ITU R.128'),
        ),
    ]
