# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-01-19 20:36
from __future__ import unicode_literals

from django.db import migrations, models


def populate_mime_types(apps, schema_editor):
    """
Add mime types for videos provided to browsers / video on demand.
"""

    FileFormat = apps.get_model('fk', 'fileformat')
    for row in FileFormat.objects.all():
        map = {
            'theora':      ('video/ogg', True),
        }
        if row.fsname in map:
            row.mime_type, row.vod_publish = map[row.fsname]
            row.save()


class Migration(migrations.Migration):

    dependencies = [
        ('fk', '0006_videofile_loudness'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileformat',
            name='mime_type',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='fileformat',
            name='vod_publish',
            field=models.BooleanField(default=False, verbose_name='Present video format to video on demand?'),
        ),
        migrations.RunPython(populate_mime_types),
    ]
