# Generated by Django 2.2.9 on 2020-04-28 10:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("fk", "0007_work_around_table_name_mishigas"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={},
        ),
    ]
