# Generated by Django 3.1.1 on 2020-12-29 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("fk", "0012_remove_videofile_old_filename"),
    ]

    operations = [
        migrations.AlterField(
            model_name="videofile",
            name="video",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="fk.video"),
        ),
    ]
