# Generated by Django 3.1.1 on 2021-04-06 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fk', '0014_videoasset'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedVideoAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.IntegerField()),
                ('asset_type', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=200)),
            ],
        ),
    ]
