apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: grafana-kubegraf
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: grafana-kubegraf
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: grafana-kubegraf
  - kind: ServiceAccount
    name: grafana-kubegraf
    namespace: default
