# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-19 20:30


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameters', models.CharField(blank=True, default='', max_length=4096)),
                ('result', models.CharField(blank=True, default='', max_length=4096)),
                ('status', models.IntegerField(choices=[(0, 'Not set'), (1, 'Pending'), (2, 'Running'), (3, 'Complete'), (4, 'Failed')], default=0)),
                ('source_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fk.VideoFile')),
                ('target_format', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fk.FileFormat')),
            ],
        ),
    ]
