apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pgbackup-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: "{{ backups_nfs_path }}"
    server: "{{ backups_nfs_host }}"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pgbackup-pvc
  namespace: "{{ namespace }}"
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
