apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pgbackup-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /srv/nfs/pgbackups
    server: 192.168.3.1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pgbackup-pvc
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
