apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fkweb
spec:
  project: default
  source:
    repoURL: https://github.com/Frikanalen/frikanalen
    targetRevision: argocd
    path: packages/fkweb
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated: {}

