name: Build ATEM control service
on:
  push:
    branches:
      - master
    paths:
      - 'packages/utils/atem-control-service/**'
jobs:
  build:
    name: Build and push Docker images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2
      - name: ATEM control service
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: frikanalen/atem-control-service
          tag_with_ref: true
          path: packages/utils/atem-control-service
          dockerfile: packages/utils/atem-control-service/Dockerfile
