name: Build next-generation playout package
on:
  push:
    branches:
      - master
    paths:
      - 'packages/playout-ng/**'
jobs:
  build:
    name: Build and push Docker images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2
      - name: Build docker
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: frikanalen/playout-ng
          tag_with_ref: true
          path: packages/playout-ng
          dockerfile: packages/playout-ng/Dockerfile
