toolbox:
  enabled: true

monitoring:
  enabled: true
  createPrometheusRules: true
  prometheusRule:
    labels:
      release: prometheus-stack

cephClusterSpec:
  dashboard:
    enabled: true
    ssl: false

ingress:
  dashboard:
    enabled: true
    host:
      name: ceph.admin.frikanalen.no
      path: /
    annotations:
      traefik.ingress.kubernetes.io/router.middlewares: default-admin-auth@kubernetescrd
      traefik.ingress.kubernetes.io/router.entrypoints: websecure

cephBlockPools:
  - name: ceph-blockpool
    spec: 
      failureDomain: host
      replicated:
        requireSafeReplicaSize: true
        size: 3
    storageClass:
      enabled: true
      name: ceph-block
      isDefault: true
      parameters:
        csi.storage.k8s.io/provisioner-secret-name: rook-csi-rbd-provisioner
        csi.storage.k8s.io/provisioner-secret-namespace: rook-ceph
        csi.storage.k8s.io/controller-expand-secret-name: rook-csi-rbd-provisioner
        csi.storage.k8s.io/controller-expand-secret-namespace: rook-ceph
        csi.storage.k8s.io/node-stage-secret-name: rook-csi-rbd-node
        csi.storage.k8s.io/node-stage-secret-namespace: rook-ceph
        pool: ceph-blockpool

cephObjectStores:
  - name: media-store
    spec:
      gateway:
        port: 80
      metadataPool:
        failureDomain: host
        replicated:
          size: 3
      dataPool:
        erasureCoded:
          codingChunks: 1
          dataChunks: 2
        failureDomain: host
    storageClass:
      enabled: false
